// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  version: env['npm_package_version'] + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'es-ES',
  supportedLanguages: ['es-ES'],
  firebaseConfig : {
    apiKey: "AIzaSyDt1ob6fDgKnIl5Rpdj_ts_ZVRWx3yHIXk",
    authDomain: "ejercicio-22a73.firebaseapp.com",
    databaseURL: "https://ejercicio-22a73-default-rtdb.firebaseio.com",
    projectId: "ejercicio-22a73",
    storageBucket: "ejercicio-22a73.appspot.com",
    messagingSenderId: "199731426733",
    appId: "1:199731426733:web:cc9dcdc3fe3bf692af5d24",
    measurementId: "G-5H9TPSN65N"
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
